#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""mythril2.py: Bug hunting on the Ethereum blockchain
http://www.github.com/avaloki108/mythril2.0
"""

from sys import exit

import mythril2.interfaces.cli

if __name__ == "__main__":
    mythril2.interfaces.cli.main()
    exit()
